# Generated by Django 5.1.2 on 2024-10-17 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_generos_usuarios_fk_generos'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='generos',
            table='generos',
        ),
    ]
